controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_torque_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    interface_name: effort

forward_velocity_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    interface_name: velocity

forward_position_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    interface_name: position

quick_stop_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    interface_name: quick_stop

spring_adjust_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    interface_name: spring_adjust

compensate_for_removed_load:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    interface_name: compensate_for_removed_load

compensate_for_added_load:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    interface_name: compensate_for_added_load
