controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    hand_guided_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    quick_stop_controller:
      type: forward_command_controller/ForwardCommandController

    spring_adjust_controller:
      type: forward_command_controller/ForwardCommandController

    compensate_for_removed_load:
      type: forward_command_controller/ForwardCommandController

    compensate_for_added_load:
      type: forward_command_controller/ForwardCommandController

    gpio_controller:
      type: gpio_controllers/GpioCommandController

hand_guided_controller:
  ros__parameters:
    joints:
      - yaw1
      - yaw2
      - elev1_j1
      - elev1_j2
      - wrist_yaw
      - wrist_pitch
      - wrist_roll
    interface_name: hand_guided

forward_velocity_controller:
  ros__parameters:
    joints:
      - yaw1
      - yaw2
      - elev1_j1
      - elev1_j2
      - wrist_yaw
      - wrist_pitch
      - wrist_roll
    interface_name: velocity

forward_position_controller:
  ros__parameters:
    joints:
      - yaw1
      - yaw2
      - elev1_j1
      - elev1_j2
      - wrist_yaw
      - wrist_pitch
      - wrist_roll
    interface_name: position

quick_stop_controller:
  ros__parameters:
    joints:
      - yaw1
      - yaw2
      - elev1_j1
      - elev1_j2
      - wrist_yaw
      - wrist_pitch
      - wrist_roll
    interface_name: quick_stop

spring_adjust_controller:
  ros__parameters:
    joints:
      - yaw1
      - yaw2
      - elev1_j1
      - elev1_j2
      - wrist_yaw
      - wrist_pitch
      - wrist_roll
    interface_name: spring_adjust

compensate_for_removed_load:
  ros__parameters:
    joints:
      - yaw1
      - yaw2
      - elev1_j1
      - elev1_j2
      - wrist_yaw
      - wrist_pitch
      - wrist_roll
    interface_name: compensate_for_removed_load

compensate_for_added_load:
  ros__parameters:
    joints:
      - yaw1
      - yaw2
      - elev1_j1
      - elev1_j2
      - wrist_yaw
      - wrist_pitch
      - wrist_roll
    interface_name: compensate_for_added_load

gpio_controller:
  ros__parameters:
    gpios:
      - wr_roll_function_enable
    command_interfaces:
      wr_roll_function_enable:
        - interfaces:
          - wr_roll_function_enable.1
