name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Adjust if you're using a different branch
  pull_request:
    branches:
      - main  # Also builds for PRs to validate

jobs:
  build-and-push:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04 for consistency

    permissions:
      contents: read
      packages: write  # Allows pushing to GHCR

    strategy:
      matrix:
        ros_distro: [humble, jazzy, rolling]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and tag the Docker image
        run: |
          cd Docker  # Navigate to the Docker folder
          docker build -f Dockerfile.${{ matrix.ros_distro }} -t ghcr.io/${{ github.repository_owner }}/synapticon_ros2_control:${{ matrix.ros_distro }} .
          docker tag ghcr.io/${{ github.repository_owner }}/synapticon_ros2_control:${{ matrix.ros_distro }} ghcr.io/${{ github.repository_owner }}/synapticon_ros2_control:${{ matrix.ros_distro }}-${{ github.sha }}

      - name: Push the Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/synapticon_ros2_control:${{ matrix.ros_distro }}
          docker push ghcr.io/${{ github.repository_owner }}/synapticon_ros2_control:${{ matrix.ros_distro }}-${{ github.sha }}
