name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Adjust if you're using a different branch
  pull_request:
    branches:
      - main  # Also builds for PRs to validate

jobs:
  build-and-push:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04 for consistency

    permissions:
      contents: read
      packages: write  # Allows pushing to GHCR

    strategy:
      matrix:
        ros_distro: [humble, jazzy, rolling]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: ROS_DISTRO=${{matrix.ROS_DISTRO}}
          tags: synapticon/synapticon_ros2_control:${{matrix.ROS_DISTRO}}
          push: true
