name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: main}
          - {ROS_DISTRO: jazzy, ROS_REPO: main}
          - {ROS_DISTRO: rolling, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}

  docker:
    strategy:
      matrix:
          ROS_DISTRO: [humble, jazzy, rolling]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: ROS_DISTRO=${{matrix.ROS_DISTRO}}
          tags: synapticon/synapticon_ros2_control:latest
          push: false